name: CICD Pipeline for Dev Branch

on:
  push:
    branches: ["dev"]

jobs:

  Install:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: your-dockerhub-username/your-angular-app
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm install
        

  Build:
    runs-on: ubuntu-latest
    needs: Install
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Build Angular App
        run: |
          npm install -g @angular/cli
          ng build
        with:
          path: portfolio
