name: CICD Pipeline for Dev Branch

on:
  push:
    branches: ["dev"]

jobs:
#Step-1
  Checkout:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: akash63/portfolio-v2
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
#Step-2        
  Install-Dependencies:
    runs-on: ubuntu-latest
    needs: Checkout
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm install
#Step-2        
  Build:
    runs-on: ubuntu-latest
    needs: Install-Dependencies
    steps:
      - name: Build Angular App
        run: |
          npm install -g @angular/cli
          ng build
#Step-3
  Docker-Image:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:latest .
      - name: Push Docker Image to Docker Hub
        run: docker push $IMAGE_NAME:latest             
#Step-4
  Docker-Container:
    runs-on: ubuntu-latest
    needs: Docker-Image
    steps: 
      - name: Create Container
        run: |
          docker run -d -p 8080:80 --name angular-container $IMAGE_NAME:latest
          sleep 10
          curl -I http://localhost:8080
